# Generated by Django 6.1.1 on 2026-09-26 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['-criado_em', '-id']},
        ),
    ]
